name: binder-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - polars
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - pip:
    - datascience
